[package]
name = "hello-action"
version = "0.1.24"
authors = ["Georg Nozicka <georg.nozicka@gmail.com>"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
