name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    uses: horowitzathome/rust-workflows/.github/workflows/check.yaml@main
  build:
    uses: horowitzathome/rust-workflows/.github/workflows/build_all.yaml@main
    needs: check
    with:
      image: horowitzathome/hello-action
      platforms: linux/amd64
      build-args: |
        RUSTARGS=--target x86_64-unknown-linux-musl
        TARGETDIR=x86_64-unknown-linux-musl/release
    secrets:
      container-registry-username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
